### ISSUE TITLE
Could we reference knockout from a CDN?

### ISSUE THREAD

**Issue by massimocode** [SMH110/My-Calculator#10]
I was thinking that since Knockout is a commonly used JS library, it's probably already in lots of people's browser caches already. If you were to reference it from a CDN then the calculator would load faster for people who have the library cached. It would also reduce load on your servers!

**Comment by SMH110** [comment]
is this right? 53124c25ace3d42fd45a1e7c755871094366287d

**Comment by massimocode** [comment]
I've commented on the commit

**Comment by SMH110** [comment]
DONE in e2b745eda4424be5fc0ba4cbc828d0aa15643925
