### ISSUE TITLE
Javascript error shown in developer tools when opening calculator.html

### ISSUE THREAD

**Issue by massimocode** [SMH110/My-Calculator#14]
I get the following error in the developer tools when opening calculator.html

"knockout-min.js:70 Uncaught Error: You cannot apply bindings multiple times to the same element."

**Comment by SMH110** [comment]
yes that right but it's work fine

**Comment by SMH110** [comment]
I don't know why it's showing this error

**Comment by massimocode** [comment]
If you had any code after ko.applyBindings then that code would not run. Read what the error is saying. Maybe try googling the error.

**Comment by SMH110** [comment]
Done in 46f093c694536e1e28f1472f8ee28772c6491169

**Comment by massimocode** [comment]
Verified
