### ISSUE TITLE
Remove code duplication

### ISSUE THREAD

**Issue by massimocode** [SMH110/My-Calculator#15]
The 2 calculators work fine side by side but it looks like you've duplicated both the calculator code and the html. You could do this without duplicating any code or html.

Your current calculator is using object oriented programming, so you can easily create several independent calculators with new Calculator(). That part will be easy.

For the html, try looking into the knockout foreach binding and binding onto an array of your calculators.

**Comment by SMH110** [comment]
Done in 46f093c694536e1e28f1472f8ee28772c6491169

**Comment by massimocode** [comment]
Verified
