### ISSUE TITLE
Ability to add/remove calculators

### ISSUE THREAD

**Issue by massimocode** [SMH110/My-Calculator#17]
I love the new feature where I can use 2 calculators side by side. But I'm thinking, it would be cool if the page started off with 1 calculator on it, but with the ability to add/remove calculators.

It would be cool if I could choose which calculator to remove as well, as opposed to just always removing the last one.

**Comment by SMH110** [comment]
Done in 0e8d2a5fdced94cac57e6337cc1c50330864ea44

**Comment by massimocode** [comment]
Verified
