### ISSUE TITLE
Multiple operations without pressing enter does not work as expected

### ISSUE THREAD

**Issue by massimocode** [SMH110/My-Calculator#18]
If I press the following buttons:
3, +, 3, +, 3, +, 3, =
I expect to see 12 on the screen, but I see 3333 instead.

**Comment by SMH110** [comment]
Are you sure about this?
Because now I tried to press these following buttons:
3+3+3+3+ 
so I got 12 when I pressed the last +

when  I pressed these following buttons : 

3+3+3+3 = 
I got 12

**Comment by massimocode** [comment]
I can't replicate after clearing my cache. I must have had an old code file cached.
