### ISSUE TITLE
The currently pressed operator appears in the display

### ISSUE THREAD

**Issue by massimocode** [SMH110/My-Calculator#2]
For example
If I click 1 and then plus and then 2, then the display reads "1+2"
When I click enter, the display reads "3"

I expect the display the read "1" when I click "1"
When I click plus, it should still read "1"
When I click "2" it should read "2"
When I click enter, it should read "3"

**Comment by SMH110** [comment]
Fixed in b324ba88403d312217c546fac0e2b00169f08d00
