### ISSUE TITLE
Operator methods have lots of duplicated code

### ISSUE THREAD

**Issue by massimocode** [SMH110/My-Calculator#24]
We could fix this by having an operator function that takes the operator as a parameter. We would keep the addDivision, addPlus, etc methods but all they would do is call this operator function. This common function would not be on the API. This would greatly reduce the amount of code we have.

**Comment by SMH110** [comment]
Done here c38b14eca8648feedad5bcaa010a5e161c65a428

**Comment by massimocode** [comment]
I've reopened this issue because it did say 

> We would keep the addDivision, addPlus, etc methods but all they would do is call this operator function

**Comment by SMH110** [comment]
Fixed here 45c012c9eeb525ca5c0a5128a9def991973a5370

**Comment by SMH110** [comment]
Finalised in https://github.com/SMH110/My-Calculator/pull/28
