### ISSUE TITLE
addZero looks like it can be deleted

### ISSUE THREAD

**Issue by massimocode** [SMH110/My-Calculator#25]
It looks like addZero could be deleted and we could use addNumber instead. Again, best we wait until we have our automated tests in place before making this change.

**Comment by SMH110** [comment]
I am working on this now

**Comment by SMH110** [comment]
Done here c38b14eca8648feedad5bcaa010a5e161c65a428

**Comment by massimocode** [comment]
I am reopening this issue because there was no need to copy the logic for addZero into addNumber and have both pieces of logic inside. It's very complicated and didn't need to be done. addZero could have simply been deleted.

**Comment by SMH110** [comment]
Fixed here 5acdca5ae1e4babcfa9eec7065fb84b1869bccd9

**Comment by SMH110** [comment]
Fixed in https://github.com/SMH110/My-Calculator/pull/28
