### ISSUE TITLE
Subsequent operations on the current total don't work as expected

### ISSUE THREAD

**Issue by massimocode** [SMH110/My-Calculator#3]
When I click 1,+,2,= I get 3 on the display
If I then click +,3,=, it says 33 instead of 6

**Comment by SMH110** [comment]
Read  the Read me file :)

**Comment by massimocode** [comment]
Ook I understand that the Readme states you need to press C to use the calculator again

But every calculator that I can ever remember using allows you to carry over the result of an operation as the first operand to a subsequent operation.

**Comment by SMH110** [comment]
This problem has been fixed.

**Comment by massimocode** [comment]
Yes this has been fixed in 80d17c26bde9a6ced59ee465bdf92d04191fd29d
