### ISSUE TITLE
Unit tests are asserting more than 1 thing

### ISSUE THREAD

**Issue by massimocode** [SMH110/My-Calculator#31]
Unit tests have more than 1 reason to fail, making them difficult to follow. It would be good to fix this.

**Comment by SMH110** [comment]
Fixed in https://github.com/SMH110/My-Calculator/pull/32

**Comment by SMH110** [comment]
Fixed here https://github.com/SMH110/My-Calculator/pull/32/commits/a448c2057484add1dd9bf3d3cd29a0cf96b5710b
