### ISSUE TITLE
Multiple calculators difficult to view on mobile

### ISSUE THREAD

**Issue by massimocode** [SMH110/My-Calculator#34]
If I open up the Chrome developer tools and click on device emulation mode and pick iPhone 5 (or 6), the calculator is tiny. If I add multiple calculators they appear side by side, same as the desktop. I think we should get rid of the hand crafted CSS and use a modern framework like Bootstrap. That way our mobile users will be happier.

**Comment by SMH110** [comment]
Now much better in https://github.com/SMH110/My-Calculator/pull/37

**Comment by massimocode** [comment]
Ok I've had a chance to pull down the code and run it up but I don't think it fixes the issue. It actually makes the calculator even worse on my laptop (not a mobile device). And it is still far too small on mobile devices. Here are some screenshots to look at:
<img width="1920" alt="screen shot 2016-06-12 at 18 06 20" src="https://cloud.githubusercontent.com/assets/3898363/15992633/83af472c-30c8-11e6-9253-b9efda670282.png">
<img width="1920" alt="screen shot 2016-06-12 at 18 06 24" src="https://cloud.githubusercontent.com/assets/3898363/15992634/83b1c880-30c8-11e6-86e9-62f68df3b0df.png">
<img width="1920" alt="screen shot 2016-06-12 at 18 05 43" src="https://cloud.githubusercontent.com/assets/3898363/15992635/83b49c90-30c8-11e6-9df1-1ad7533ebbf7.png">
<img width="1920" alt="screen shot 2016-06-12 at 18 05 48" src="https://cloud.githubusercontent.com/assets/3898363/15992636/83b70d72-30c8-11e6-8d6c-133d0091b309.png">
<img width="1920" alt="screen shot 2016-06-12 at 18 05 55" src="https://cloud.githubusercontent.com/assets/3898363/15992637/83b99588-30c8-11e6-8873-d1c5b8504133.png">
<img width="1920" alt="screen shot 2016-06-12 at 18 05 59" src="https://cloud.githubusercontent.com/assets/3898363/15992638/83bb6f2a-30c8-11e6-9f5d-6b782ac3e142.png">

**Comment by SMH110** [comment]
Now it's work on Desktop, ipad, galaxy s3,s4,s5 , iphone 6

**Comment by SMH110** [comment]
NOW IT'S HAS BEEN FIXED HERE c96cdfac2131d35ac3549ba1eeeb5009196b77bf :)
