### ISSUE TITLE
Using multiple operators results in strange behaviour

### ISSUE THREAD

**Issue by massimocode** [SMH110/My-Calculator#8]
Replication steps:
Perform the following operations in strict order
1) 1 + 1 = (correctly displays 2)
2) + - 1 = (displays 3 instead of 1)

This does not match common calculator behaviour

**Comment by massimocode** [comment]
Another simpler example:
1) 3 * - 1 = (displays 3 instead of 2)

I tried this on my Windows Phone calculator, my Android tablet calculator and my Mac calculator and all of them displayed 2. I think the last pressed operator should be used.

**Comment by SMH110** [comment]
This bug has been fixed in 731437d3d65e7ccffb53a8fd5a945b2439567d89

**Comment by massimocode** [comment]
I have verified this has been fixed
